engine_config:
  app_to_engine_socket: "ipc://app_to_engine.sock"

worker_client_config:
  type: "sync"
  input_path: "ipc://input_fastapi.sock"
  output_path: "ipc://output_fastapi.sock"
  num_workers: 32

scheduler_config:
  type: "round_robin"
  max_batch_size: 128
  num_workers: 32 